In [27]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

arr = pd.DataFrame([["a"],
                    ["b"], 
                    ["c"], 
                    ["d"], 
                    ["a"], 
                    ["b"], 
                    ["a"]], columns=["letters"])
prev_cov = np.array(arr.loc[:, "letters"].astype("category"))[:, None]
print(prev_cov)

if len(prev_cov.shape) > 2:
	print("hello")
	prev_cov = np.squeeze(prev_cov, axis=1)
print(prev_cov)

if not np.array_equal(prev_cov, prev_cov.astype(bool)):
	enc = OneHotEncoder(handle_unknown="ignore")  # create OHE
	prev_cov = enc.fit_transform(prev_cov).toarray()  # fit OHE

print(prev_cov)
print(arr.loc[:, "letters"].shape)
    

[['a']
 ['b']
 ['c']
 ['d']
 ['a']
 ['b']
 ['a']]
[['a']
 ['b']
 ['c']
 ['d']
 ['a']
 ['b']
 ['a']]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]
(7,)


In [12]:
from patsy import ModelDesc, dmatrix
content="~letters"

yvar = arr.loc[:, "letters"].astype("category")
yvarlevels = set(yvar)
betaindex = np.array(yvar.cat.codes)

if yvar.isnull().any().any():
	raise ValueError("Your content covariate contains missing values. All values of the content covariate must be observed.")

print(yvar)
print(yvarlevels)
print(betaindex)

ValueError: Your content covariate contains missing values. All values of the content covariate must be observed.